tools:
  shell:
    allow:
      - "git log *"
      - "find *"
      - "grep *"
      - "ls *"
      - Get-ChildItem *
      - Where-Object { *
      - Select-Object FullName
      - dir *
    deny:
      - "rm *"
